name: ControllableMobsAPI
main: de.ntcomputer.minecraft.controllablemobs.plugin.ControllableMobsAPIPlugin
version: ${version}
load: STARTUP
author: DevCybran
website: http://dev.bukkit.org/bukkit-plugins/controllable-mobs-api/
description:
    This plugin is wrapping an API for enhanced mob control.
    By itself it has no effect, but it is used by several other plugins.